/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package finalproj.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MovieGenre {
  Comedy, Romance, Adventure, Action, Animation, Children, Crime, Documentary, Drama, Fantasy, FilmNoir, Horror, Musical, Mystery, SciFi, Thriller, War, Western, nogenreslisted, IMAX  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MovieGenre\",\"namespace\":\"finalproj.model\",\"symbols\":[\"Comedy\",\"Romance\",\"Adventure\",\"Action\",\"Animation\",\"Children\",\"Crime\",\"Documentary\",\"Drama\",\"Fantasy\",\"FilmNoir\",\"Horror\",\"Musical\",\"Mystery\",\"SciFi\",\"Thriller\",\"War\",\"Western\",\"nogenreslisted\",\"IMAX\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
