/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package stubs.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GameType {
  TexasHoldem, Blackjack, PaiGow, FiveCardDraw  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GameType\",\"namespace\":\"stubs.model\",\"symbols\":[\"TexasHoldem\",\"Blackjack\",\"PaiGow\",\"FiveCardDraw\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
